auth/urls.py
from django.urls import path
from .views import RegisterView, LoginView, LogOutView

app_name = 'auth'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogOutView.as_view(), name='logout'),


]

evento/urls.py
from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from evento.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('accounts.urls')),
    path('events/', include('events.urls')),
    path('', HomeView.as_view(), name='home')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

events/urls.py
from django.urls import path
from events.views import EventCreateView, MyEventView, EventView, EventDeleteView, EventUpdateView

app_name = 'events'

urlpatterns = [
    path('', EventView.as_view(), name="view_events" ),
    path('my-events', MyEventView.as_view(), name="my_events" ),
    path('create/', EventCreateView.as_view(), name="create_event" ),
    path('delete/<int:pk>', EventDeleteView.as_view(), name="delete_event" ),
    path('update/<int:pk>', EventUpdateView.as_view(), name="update_event" ),

]

templates/includes/form_fields.html
{% load widget_tweaks %}

    {{ field.label_tag }}

    {% if form.is_bound %}
      {% if field.errors %}
        {% render_field field class="form-control input-text is-invalid" %}
        {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}
        {% render_field field class="form-control input-text is-valid" %}
      {% endif %}
    {% else %}
      {% render_field field class="form-control input-text" %}
    {% endif %}

    {% if field.help_text %}
      <small class="form-text text-muted">{{ field.help_text }}</small>
    {% endif %}

templates/includes/header.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="{% url 'home' %}">Evento</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    {% url 'home' as home %}
    {% url 'events:view_events' as events %}



    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == home %} active {%endif%}">
        <a class="nav-link" href="{% url 'home' %}">Home </a>
      </li>
      <li class="nav-item {% if request.path == events %} active {%endif%}">
        <a class="nav-link" href="{% url 'events:view_events' %}">Events</a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      {% if request.user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ request.user.username }}</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="{% url 'events:create_event' %}">Create Event</a>
              <a class="dropdown-item" href="{% url 'events:my_events' %}">My events</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'auth:logout' %}">Log Out</a>
          </li>
      {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'auth:login' %}">Login </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'auth:register' %}">Register</a>
          </li>
      {% endif %}
    </ul>
  </div>
</nav>

templates/includes/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}

templates/includes/otp.html
<!DOCTYPE html>
<html>
  <head>

        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>Login OTP</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style type="text/css">
        /**
         * Google webfonts. Recommended to include the .woff version for cross-client compatibility.
         */
        @media screen {
          @font-face {
            font-family: 'Merriweather';
            font-style: normal;
            font-weight: 400;
            src: local('Merriweather'), local('Merriweather'), url(http://fonts.gstatic.com/s/merriweather/v8/ZvcMqxEwPfh2qDWBPxn6nmB7wJ9CoPCp9n30ZBThZ1I.woff) format('woff');
          }
          @font-face {
            font-family: 'Merriweather Bold';
            font-style: normal;
            font-weight: 700;
            src: local('Merriweather Bold'), local('Merriweather-Bold'), url(http://fonts.gstatic.com/s/merriweather/v8/ZvcMqxEwPfh2qDWBPxn6nhAPw1J91axKNXP_-QX9CC8.woff) format('woff');
          }
        }
        /**
         * Avoid browser level font resizing.
         * 1. Windows Mobile
         * 2. iOS / OSX
         */
        body,
        table,
        td,
        a {
          -ms-text-size-adjust: 100%; /* 1 */
          -webkit-text-size-adjust: 100%; /* 2 */
        }
        /**
         * Remove extra space added to tables and cells in Outlook.
         */
        table,
        td {
          mso-table-rspace: 0pt;
          mso-table-lspace: 0pt;
        }
        /**
         * Better fluid images in Internet Explorer.
         */
        img {
          -ms-interpolation-mode: bicubic;
        }
        /**
         * Remove blue links for iOS devices.
         */
        a[x-apple-data-detectors] {
          font-family: inherit !important;
          font-size: inherit !important;
          font-weight: inherit !important;
          line-height: inherit !important;
          color: inherit !important;
          text-decoration: none !important;
        }
        /**
         * Fix centering issues in Android 4.4.
         */
        div[style*="margin: 16px 0;"] {
          margin: 0 !important;
        }
        body {
          width: 100% !important;
          height: 100% !important;
          padding: 0 !important;
          margin: 0 !important;
        }
        /**
         * Collapse table borders to avoid space between cells.
         */
        table {
          border-collapse: collapse !important;
        }
        a {
          color: white;
        }
        img {
          height: auto;
          line-height: 100%;
          text-decoration: none;
          border: 0;
          outline: none;
        }
        </style>

  </head>
  <body>

        <!-- start body -->
        <table border="0" cellpadding="0" cellspacing="0" width="100%">

          <!-- start logo -->
          <tr>
            <td align="center">
              <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
                <tr>
                  <td align="center" valign="top" style="padding: 36px 24px;">
                    <a href="http://localhost:8000" target="_blank"  style="display: inline-block;">
                      <img src="https://www.theeventscompany.co.uk/wp-content/uploads/2016/04/logo@2x.png" alt="Logo" border="0" width="500" style="display: block; width: 500px; max-width: 500px; min-width: 500px;">
                    </a>
                  </td>
                </tr>
              </table>

            </td>
          </tr>
          <!-- end logo -->


          <!-- start copy block -->
          <tr>
            <td align="center">

              <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">

                <!-- start copy -->
                <tr>
                  <td bgcolor="#ffffff" align="left" style="padding: 24px; font-size: 16px; line-height: 24px;">
                    <h3 align="center" style="margin: 0 0 12px; font-family: 'Merriweather Bold', serif; font-size: 32px; font-weight: 400; line-height: 48px; "><b style="color:#352853;">OTP: {{ data.otp }}</b></h3>
                    <p style="font-family: 'Merriweather', serif; margin: 0;">Use the code to Login </p>
                  </td>
                </tr>
                <!-- end copy -->



                <!-- start copy -->
                <tr>
                  <td align="left" bgcolor="#ffffff" style="padding: 24px; font-family: 'Merriweather', serif; font-size: 16px; line-height: 24px; border-bottom: 5px solid #352853">
                    <p style="margin: 0;">Cheers,<br><span style="color:#352853;"> Envento Team<span></p>
                  </td>
                </tr>
                <!-- end copy -->

              </table>
            </td>
          </tr>
          <!-- end copy block -->


        </table>
        <!-- end body -->

  </body>
</html>

templates/includes/welcome.html
<!DOCTYPE html>
<html>
  <head>

        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>Welcome To Envento</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style type="text/css">
        /**
         * Google webfonts. Recommended to include the .woff version for cross-client compatibility.
         */
        @media screen {
          @font-face {
            font-family: 'Merriweather';
            font-style: normal;
            font-weight: 400;
            src: local('Merriweather'), local('Merriweather'), url(http://fonts.gstatic.com/s/merriweather/v8/ZvcMqxEwPfh2qDWBPxn6nmB7wJ9CoPCp9n30ZBThZ1I.woff) format('woff');
          }
          @font-face {
            font-family: 'Merriweather Bold';
            font-style: normal;
            font-weight: 700;
            src: local('Merriweather Bold'), local('Merriweather-Bold'), url(http://fonts.gstatic.com/s/merriweather/v8/ZvcMqxEwPfh2qDWBPxn6nhAPw1J91axKNXP_-QX9CC8.woff) format('woff');
          }
        }
        /**
         * Avoid browser level font resizing.
         * 1. Windows Mobile
         * 2. iOS / OSX
         */
        body,
        table,
        td,
        a {
          -ms-text-size-adjust: 100%; /* 1 */
          -webkit-text-size-adjust: 100%; /* 2 */
        }
        /**
         * Remove extra space added to tables and cells in Outlook.
         */
        table,
        td {
          mso-table-rspace: 0pt;
          mso-table-lspace: 0pt;
        }
        /**
         * Better fluid images in Internet Explorer.
         */
        img {
          -ms-interpolation-mode: bicubic;
        }
        /**
         * Remove blue links for iOS devices.
         */
        a[x-apple-data-detectors] {
          font-family: inherit !important;
          font-size: inherit !important;
          font-weight: inherit !important;
          line-height: inherit !important;
          color: inherit !important;
          text-decoration: none !important;
        }
        /**
         * Fix centering issues in Android 4.4.
         */
        div[style*="margin: 16px 0;"] {
          margin: 0 !important;
        }
        body {
          width: 100% !important;
          height: 100% !important;
          padding: 0 !important;
          margin: 0 !important;
        }
        /**
         * Collapse table borders to avoid space between cells.
         */
        table {
          border-collapse: collapse !important;
        }
        a {
          color: white;
        }
        img {
          height: auto;
          line-height: 100%;
          text-decoration: none;
          border: 0;
          outline: none;
        }
        </style>

  </head>
  <body>

        <!-- start body -->
        <table border="0" cellpadding="0" cellspacing="0" width="100%">

          <!-- start logo -->
          <tr>
            <td align="center">
              <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
                <tr>
                  <td align="center" valign="top" style="padding: 36px 24px;">
                    <a href="http://localhost:8000" target="_blank"  style="display: inline-block;">
                      <img src="https://www.theeventscompany.co.uk/wp-content/uploads/2016/04/logo@2x.png" alt="Logo" border="0" width="500" style="display: block; width: 500px; max-width: 500px; min-width: 500px;">
                    </a>
                  </td>
                </tr>
              </table>

            </td>
          </tr>
          <!-- end logo -->


          <!-- start copy block -->
          <tr>
            <td align="center">

              <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">

                <!-- start copy -->
                <tr>
                  <td bgcolor="#ffffff" align="left" style="padding: 24px; font-size: 16px; line-height: 24px;">
                    <h3 align="center" style="margin: 0 0 12px; font-family: 'Merriweather Bold', serif; font-size: 32px; font-weight: 400; line-height: 48px; "><b style="color:#352853;">WELCOME, ABOARD!</b></h3>
                    <p style="font-family: 'Merriweather', serif; margin: 0;">Thank you {{ data.username }} for signing up with Envento. We strive to bring you the best events all aound.</p>
                  </td>
                </tr>
                <!-- end copy -->

                <!-- start button -->
                <tr>
                  <td align="left" bgcolor="#ffffff">
                    <table border="0" cellpadding="0" cellspacing="0" width="100%">
                      <tr>
                        <td align="center" bgcolor="#ffffff" style="padding: 12px;">
                          <table border="0" cellpadding="0" cellspacing="0">
                            <tr>
                              <td align="center" bgcolor="#352853" style="border-radius: 6px;">
                                <a href="http://localhost:8000/auth/login/" target="_blank"  style="display: inline-block; padding: 16px 36px; font-family: 'Merriweather', serif; font-size: 16px; color: #ffffff; text-decoration: none; border-radius: 6px; cursor: pointer;">Login</a>
                              </td>
                            </tr>
                          </table>
                        </td>
                      </tr>
                    </table>
                  </td>
                </tr>
                <!-- end button -->

                <!-- start copy -->
                <tr>
                  <td align="left" bgcolor="#ffffff" style="padding: 24px; font-family: 'Merriweather', serif; font-size: 16px; line-height: 24px; border-bottom: 5px solid #352853">
                    <p style="margin: 0;">Cheers,<br><span style="color:#352853;"> Envento Team<span></p>
                  </td>
                </tr>
                <!-- end copy -->

              </table>
            </td>
          </tr>
          <!-- end copy block -->


        </table>
        <!-- end body -->

  </body>
</html>