auth/urls.py
from django.urls import path
from .views import RegisterView, LoginView, LogOutView

app_name = 'auth'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogOutView.as_view(), name='logout'),


]

evento/urls.py
from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from evento.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('accounts.urls')),
    path('events/', include('events.urls')),
    path('', HomeView.as_view(), name='home')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

events/urls.py
from django.urls import path
from events.views import EventCreateView, MyEventView, EventView, EventDeleteView, EventUpdateView

app_name = 'events'

urlpatterns = [
    path('', EventView.as_view(), name="view_events" ),
    path('my-events', MyEventView.as_view(), name="my_events" ),
    path('create/', EventCreateView.as_view(), name="create_event" ),
    path('delete/<int:pk>', EventDeleteView.as_view(), name="delete_event" ),
    path('update/<int:pk>', EventUpdateView.as_view(), name="update_event" ),

]

events/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models.signals import pre_save
from evento.utils import unique_slug_generator

# Create your models here.


class Event(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    venue = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, max_length=255)
    description = models.TextField()
    date = models.DateField()
    created_on = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    class Meta:
        permissions = (
            ('can_create', "Can Create Event"),
            ('can_delete_event', "Can Delete Event")
        )



def slug_save(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance, instance.name, instance.slug)


pre_save.connect(slug_save, sender=Event)

events/forms.py
from django import forms
from events.models import Event


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['name','venue', 'description', 'date']
        widgets = {
        'date': forms.DateInput(format=('%m/%d/%Y'), attrs={'class':'form-control', 'placeholder':'Select a date', 'type':'date'}),
                    }

events/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from events.models import Event
from events.forms import EventForm
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib import messages

# Create your views here.

class EventCreateView(LoginRequiredMixin, CreateView):
    model = Event
    template_name = 'events/create_event.html'
    form_class = EventForm

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.created_by = self.request.user
        obj.save()
        messages.success(self.request ,f'Event Successfully Added!')
        return redirect('events:create_event')

class EventView(ListView):
    model = Event
    template_name = 'events/event_view.html'


class MyEventView(LoginRequiredMixin, ListView):
    model = Event
    template_name = 'events/my_event.html'

    def get_queryset(self):
        owner = self.request.user
        return self.model.objects.filter(created_by=owner)

class EventDeleteView(LoginRequiredMixin, DeleteView):
    model = Event
    success_url = reverse_lazy('events:view_events')

    def get_queryset(self):
        owner = self.request.user
        messages.success(self.request ,f'Event Deleted Successfully!')
        return self.model.objects.filter(created_by=owner)

class EventUpdateView(LoginRequiredMixin, UpdateView):
    model = Event
    fields = ['name', 'date', 'venue', 'description']
    template_name = 'events/event_update.html'
    success_url = reverse_lazy('events:view_events' )

    def get_queryset(self):
        owner = self.request.user
        return self.model.objects.filter(created_by=owner)

templates/events/create_event.html
{% extends 'base.html' %}
{% block content %}

<section class="container">

  <div class="row justify-content-center mt-5">

    <div class="col-md-8 col-xs-12">
       <form class="event_create_form" method="post" action="">
         {% csrf_token %}
         <legend class="text-center">Create Event</legend>
         <hr>
         {% include 'includes/messages.html' %}
         <div class="form-row">
           <div class="col-md-4">
             {% include 'includes/form_fields.html' with field=form.name %}
           </div>
           <div class="col-md-4">
             {% include 'includes/form_fields.html' with field=form.venue %}
           </div>
           <div class="col-md-4">
             {% include 'includes/form_fields.html' with field=form.date %}
           </div>
         </div>
         <div class="form-row">
           <div class="col">
             {% include 'includes/form_fields.html' with field=form.description %}
           </div>
         </div>


         <div class="mt-3">
           <button class="btn btn-lg btn-primary btn-block" type="submit">Create</button>
         </div>
       </form>
     </div>
   </div>
</section>

{% endblock %}

templates/events/event_confirm_delete.html
<!-- Modal -->
<div class="modal fade" id="eventdeleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete Event</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="post" action="{% url 'events:delete_event' pk=event.pk %}">
            {% csrf_token %}
            <p>Are you sure you want to delete {{ event.name }}?</p>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <input type="submit" class="btn btn-danger" value="Confirm">
        </form>
      </div>
    </div>
  </div>
</div>

templates/events/event_update.html
{% extends 'base.html' %}
{% block content %}

<section class="container">

  <div class="row justify-content-center mt-5">

    <div class="col-md-8 col-xs-12">
       <form method="post" action="">
         {% csrf_token %}
         <legend class="text-center">Update Event</legend>
         <hr>
         {% include 'includes/messages.html' %}
         <div class="form-row">
           <div class="col-md-4">
             {% include 'includes/form_fields.html' with field=form.name %}
           </div>
           <div class="col-md-4">
             {% include 'includes/form_fields.html' with field=form.venue %}
           </div>
           <div class="col-md-4">
             {% include 'includes/form_fields.html' with field=form.date %}
           </div>
         </div>
         <div class="form-row">
           <div class="col">
             {% include 'includes/form_fields.html' with field=form.description %}
           </div>
         </div>


         <div class="mt-3">
           <button class="btn btn-lg btn-primary btn-block" type="submit">Update Event</button>
         </div>
       </form>
     </div>
   </div>
</section>

{% endblock %}

templates/events/event_view.html
{% extends 'base.html' %}
{% block content %}

<section class="container">

  <div class="row justify-content-center mt-5">

    <div class="col-md-8 col-xs-12">
      {% include 'includes/messages.html' %}

          {% for event in object_list %}

          <div class="card">
            <div class="card-body">
              <h5 class="card-title text-primary">{{ event.name }} <small class="text-muted">{{ event.date }}</small></h5>
               <small class="text-dark">Venue: {{ event.venue }}</small>
              <p class="card-text">{{ event.description }}</p>
              <a href="#" class="btn btn-primary">Attend</a>
            </div>
          </div>
          <hr>
          {% endfor %}
     </div>
     <div class="col-md-4 col-xs-12">
       <div class="card">
         <div class="card-body">
           <h5 class="card-title">Filter</h5>
           <hr>
         </div>
       </div>

      </div>
   </div>


</section>

{% endblock %}

templates/events/my_event.html
{% extends 'base.html' %}
{% block content %}

<section class="container">

  <div class="row justify-content-center mt-5">

    <div class="col-md-8 col-xs-12">
      {% include 'includes/messages.html' %}

        <ul class="list-group list-group-flush">
          {% for event in object_list %}
          {% include 'events/event_confirm_delete.html' %}
           <li class="list-group-item">{{ event.name }} <span class="float-right"><a class="btn btn-primary" href="{% url 'events:update_event' pk=event.pk %}">Update</a> <a class="btn btn-danger"  data-toggle="modal" data-target="#eventdeleteModal">Delete</a></span></li>
          {% endfor %}
        </ul>
     </div>
   </div>


</section>

{% endblock %}